import { z } from "zod";
import type {
  GetResponse,
  Invocation,
  QueryResponse,
  ResultReference,
} from "../../jmap/types/core.js";
import { CAPABILITY_CORE, CAPABILITY_SIEVE } from "../../jmap/types/core.js";
import type {
  SieveScript,
  SieveScriptComparator,
  SieveScriptFilterCondition,
  SieveScriptGetArguments,
  SieveScriptQueryArguments,
} from "../../jmap/types/sieve.js";
import { defineTool } from "../../registry/define-tool.js";
import { renderFields, renderTable } from "../../shared/render.js";
import {
  describeScripts,
  isVacationScript,
  renderScriptRow,
  renderScriptText,
  SCRIPT_COLUMNS,
  SCRIPT_PROPERTIES,
  scriptText,
} from "./script.js";

/**
 * `queryMaxResults` defaults to 5000 and is advertised nowhere: always send a
 * limit. An account holds a handful of scripts, so one page is the whole set and
 * this listing needs no cursor.
 */
const MAX_LIMIT = 100;

/** Name ascending: the one order a person scanning their filters expects. */
const BY_NAME: SieveScriptComparator[] = [{ property: "name", isAscending: true }];

const inputSchema = z
  .strictObject({
    action: z
      .enum(["list", "show"])
      .describe("What to do: list the scripts of the account, or read the text of one of them."),
    nameContains: z
      .string()
      .optional()
      .describe("On list, keep only the scripts whose name contains this. Ignored on show."),
    id: z
      .string()
      .optional()
      .describe("On show, the id of the script to read, as list returns it. Required on show."),
  })
  .refine((input) => input.action !== "show" || input.id !== undefined, {
    message: "Name the script to read with `id`.",
    path: ["id"],
  });

export const sieveScripts = defineTool({
  name: "sieve_scripts",
  title: "Read Sieve scripts",
  description:
    "Reads the Sieve filters of the account. `list` gives one line per script — its name, its id, " +
    "and whether it is the active one — and says which script is currently filtering incoming " +
    "mail, or that none is. `show` returns the full source of one script. " +
    "Only one script filters at a time: storing or editing a script changes nothing until it is " +
    "activated, which sieve_write does. " +
    "A script named `vacation` is generated by the vacation response and is read and changed " +
    "through vacation_manage, never through this tool.",
  inputSchema,
  classes: ["read"],
  classify: () => "read",
  summarize: (input) =>
    input.action === "show"
      ? `Read the source of Sieve script ${input.id}.`
      : "List the Sieve scripts of the account.",
  run: async (input, context) => {
    const { client, session } = context;

    if (input.action === "show") {
      // Narrowed by the refinement above, which the registry parses before this
      // runs; restated because the schema types the branch, not the field.
      const id = input.id;
      if (id === undefined) return { text: "Refused: name the script to read with `id`." };

      const args: SieveScriptGetArguments = {
        accountId: session.accountId,
        ids: [id],
        properties: [...SCRIPT_PROPERTIES],
      };
      const response = await client.request<GetResponse<SieveScript>>(
        [CAPABILITY_CORE, CAPABILITY_SIEVE],
        ["SieveScript/get", args, "0"],
      );

      const script = response.list.find((candidate) => candidate.id === id);
      if (script === undefined) {
        // Answered off the read alone: no download is attempted for an id the
        // account does not hold, and the refusal names the id rather than the
        // empty result.
        return {
          text:
            `Refused: no Sieve script has the id ${id}. Run sieve_scripts with action list to see ` +
            "what the account holds.",
        };
      }

      const { blobId } = script;
      if (blobId === undefined) {
        return {
          text: `Refused: ${describeScripts([script])} carries no blobId, so the server has no source to hand back for it.`,
        };
      }

      const text = await scriptText(script, context);

      const header = renderFields({
        script: script.name ?? "(unnamed)",
        id: script.id,
        active: script.isActive === true ? "yes — this script filters incoming mail" : "no",
        note: isVacationScript(script)
          ? "generated by the vacation response; change it with vacation_manage, not sieve_write"
          : undefined,
      });

      return { text: `${header}\n\n${renderScriptText(text)}` };
    }

    const filter = buildFilter(input.nameContains);
    const queryArguments: SieveScriptQueryArguments = {
      accountId: session.accountId,
      filter,
      sort: BY_NAME,
      position: 0,
      limit: MAX_LIMIT,
      calculateTotal: true,
    };

    const idsFromQuery: ResultReference = {
      resultOf: "0",
      name: "SieveScript/query",
      path: "/ids",
    };

    // One round trip for both: the get takes its ids off the query by
    // back-reference rather than waiting for the answer to come back first.
    const calls: Invocation[] = [
      ["SieveScript/query", queryArguments, "0"],
      [
        "SieveScript/get",
        {
          accountId: session.accountId,
          "#ids": idsFromQuery,
          properties: [...SCRIPT_PROPERTIES],
        },
        "1",
      ],
    ];

    const [query, fetched] = await client.requestMany<[QueryResponse, GetResponse<SieveScript>]>(
      [CAPABILITY_CORE, CAPABILITY_SIEVE],
      calls,
    );

    const scripts = inQueryOrder(query.ids, fetched.list);
    const count = `${query.total ?? scripts.length} script(s)${
      input.nameContains === undefined ? "" : ` matching "${input.nameContains}"`
    }, ${scripts.length} shown.`;

    const header = `${count} ${describeActive(scripts, input.nameContains !== undefined)}`;
    const table = renderTable(scripts.map(renderScriptRow), SCRIPT_COLUMNS);

    return { text: `${header}\n\n${table}` };
  },
});

/** The one condition this listing may send. An empty filter lists everything. */
function buildFilter(nameContains: string | undefined): SieveScriptFilterCondition {
  return nameContains === undefined ? {} : { name: nameContains };
}

/** The query fixes the order; the get answers in whatever order it likes. */
function inQueryOrder(ids: readonly string[], scripts: readonly SieveScript[]): SieveScript[] {
  const byId = new Map(scripts.map((script) => [script.id, script]));
  return ids
    .map((id) => byId.get(id))
    .filter((script): script is SieveScript => script !== undefined);
}

/**
 * Which script filters incoming mail, in a sentence rather than a column.
 *
 * The "none" wording is a claim about the account, so it is only made when the
 * listing spans the account. Under a name filter the active script may simply
 * not match, and saying nothing filters would be false.
 */
function describeActive(scripts: readonly SieveScript[], filtered: boolean): string {
  const active = scripts.find((script) => script.isActive === true);

  if (active !== undefined) {
    const which = `${active.name ?? "(unnamed)"} (${active.id})`;
    return isVacationScript(active)
      ? `The vacation response is what is active — ${which} — so no filtering script is running.`
      : `${which} is active and filters incoming mail.`;
  }

  return filtered
    ? "None of the matching scripts is the active one."
    : "No script is active: nothing filters incoming mail right now.";
}
